disqus: davejlong
url: http://arcane-lake-4040.herokuapp.com/

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['public', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']
destination: 'public'
