disqus: davejlong
url: http://davejlong.com

permalink: /:year/:month/:day/:title/
paginate: 10
markdown: RDiscount

exclude: ['public', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']
destination: 'public'
